### PR TITLE
[PR] Creating basic demo on both `inline` and `Material` datetime pickers

### LINKED ISSUE #1: Feat: Setup + Document `date` and `time` input in a `Flutter` App
As noted by @panoramix360 in https://github.com/dwyl/mvp/issues/140#issuecomment-1629885618 
the `MVP` currently has `text` `input` for updating the `timer.start` and `timer.stop`: 

image

# Todo

+ [x] Follow the instructions in the core [`Material`](https://api.flutter.dev/flutter/material/material-library.html) library to implement the [`DatePicker`](https://api.flutter.dev/flutter/material/DatePickerDialog-class.html) and [`TimePicker`](https://api.flutter.dev/flutter/material/TimePickerDialog-class.html) widgets and allow a `person` to interact with a [`DateTime`](https://api.flutter.dev/flutter/dart-core/DateTime-class.html) object. 

> **Note**: The data does not need to be persisted to a "backend"; just on the device is fine. 📱 
But if you want to get creative / use your imagination and make it a "guess the date game", that's fine too. 💭 

+ [ ] Once we've figured out the "basics" of the `Material UI` widgets, 
explore a more intuitive and _faster_ interface.
  ***Specifically*** we don't want a "[Modal](https://github.com/dwyl/product-ux-research/issues/38)" (Dialog) for inputting the `DateTime`. We want the `timers` input to expand below the `item` the way it currently does in the `MVP` so no context is lost.

+ [ ] Ensure the `App` is deployed via `GitHub Pages` as a `PWA`. 📱 

# Research

There are _many_ options available, e.g: https://fluttergems.dev/date-time-picker
image

Please feel free to do more research into this but remember to capture all of it.
And don't get _tooo_ carried away as this feature is meant to be simple. 👌

### PR DESCRIPTION
**Pull request by LuchoTurtle**
closes #1 

This PR  implements both `Material` (through `datePicker` and `timePicker`) and `inline` scenarios for mutating `DateTime` objects in `Flutter`.
The `README` documents the process on both occasions and is also tested.

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
@nelsonic 
This should be reviewable and mergeable. 
I've added tests to cover each scenario and GH workflow to run these tests.
I've also added a simple incrementing counter to showcase how easy it is to use callbacks to track how many times the person is updating the `dateTime` field.

**I didn't add a deploy workflow**. I want to leave this for a separate PR.

**Review by nelsonic — APPROVED** [review]
@LuchoTurtle Looks good. Thanks.👌

**Comment by panoramix360** [comment]
👀

That's really nice guys!

**Comment by LuchoTurtle** [comment]
It's just a simple demo @panoramix360 but thanks 😍

**Pull request merged**
